### ISSUE TITLE
установка на mac

### ISSUE THREAD

**Issue by n-osennij** [rupor-github/fb2converter#10]
Есть ли возможность установить на mac? Как это сделать?

**Comment by rupor-github** [comment]
Я думаю что конкретно МАКовские вопросы лучше задавать на форуме - там у людей немало mac'ов. Но вобщем я не вполне понимаю вопрос. В releases есть сборка для Darwin - распаковываем в терминале и вперед. Все как и везде - это не GUI app.

**Comment by n-osennij** [comment]
не знал про Darwin, на маке совсем недавно. Да, попробовал скачать, запустить - работает. Спасибо!
