### ISSUE TITLE
Проблема с метаданными при конвертации

### ISSUE THREAD

**Issue by snupt** [rupor-github/fb2converter#2]
Привет!

При конвертации из fb2 в mobi теряется часть информации, которая хранится в структуре FB2.

Вот так выглядит метадата в Calibre после конвертации через fb2conv из fb2 в mobi:

<img width="1610" alt="Screenshot 2019-12-03 at 10 57 29" src="https://user-images.githubusercontent.com/1439183/70031164-b7816680-15bb-11ea-9b94-fba67d22eb7e.png">

А вот так она выглядит после конвертации через встроенный конвертор Calibre:

<img width="1610" alt="Screenshot 2019-12-03 at 11 03 31" src="https://user-images.githubusercontent.com/1439183/70031588-9d945380-15bc-11ea-856c-0ddb95e0aa02.png">

А волнует меня это только по той причине, что файл сконвертированный в Calibre с корректно проставленным asin (я подозреваю в этом дело) может нормально работать с сервисом Goodreads при попадании в Kindle. Весьма полезная фича.

**Comment by rupor-github** [comment]
Насколько я понял для работы GoodReads нужен только правильный ASIN. В структуре FB2 никакого ASIN никогда не было - этого просто нет в стандарте FB2. В качестве book id в FB2 конечно можно написать любую строку - но обычно используется UUID.  Если ASIN где-то и лежит - мне об этом неизвестно. Так что информация при конвертировании не пропадает, все что можно и нужно - используется как должно.  Calibre, как я понял, имеет средства для поиска ASIN, это не очень сложно при наличии интернета. Например этим занимается кнопка "download metadata".  В задачу этого конвертера поиск правильного ASIN и прописывание его в AZW3 с целью интеграции в GoodRead никогда не входило и у меня нет желания расширять функциональность в этом направлении.

**Comment by snupt** [comment]
Да, судя по всему, спека fb2 не предполагает asin. Там есть только тег для isbn. Однако, я не предлагаю расширять программу то парсинга страниц амазона. Мне нравится fb2c как инструмент и я ищу **любой** способ решить проблему. Тег можно подсунуть через аргумент (аля --asin) или конфигурационный файл (есть же там overwrites, например). Think about it.

**Comment by rupor-github** [comment]
See issue #3
