### ISSUE TITLE
Converter to EPUB fails on tne XML diacritics

### ISSUE THREAD

**Issue by proninyaroslav** [rupor-github/fb2converter#22]
At first I tried to convert the book via Telegram bot, but it didn't get any errors and it's simply didn't convert. So I decided to convert it manually. It was found that if fb2 contains diacritics (in my case it's the Nordic letter å (`&aring;`), then the converter gives an error:

`ERROR	Unable to process file	{"file": "/home/yaroslav/Викернес В. - Речи Варга - 2001.fb2", "error": "unable to parse FB2: XML syntax error on line 27: invalid character entity &aring;"}`

This book:
[Викернес В. - Речи Варга - 2001.zip](https://github.com/user-attachments/files/16578805/-.-.2001.zip)

For example, this book opens successfully in Librera Reader.

**Comment by rupor-github** [comment]
If I understand [XML properly](https://en.wikipedia.org/w/index.php?title=List_of_XML_and_HTML_character_entity_references&mobile-app=true&theme=dark) there are only 5 XML entities which require such support: amp, lt, gt, quot, apos. The one you encounter is coming from HTML where set is much bigger, but FB2 is XML, not HTML and as such I think parser is right. XML Notepad, for example gives 
![image](https://github.com/user-attachments/assets/6db1c7b5-0c50-41c0-b884-d861b7716abc)
when opening this file (which is not UTF8, by the way, but rather Windows1251 encoding). So I am not really sure I should do anything about it - this case is quite rare and it is probably easier to convert file to UTF8 and use ''å" directly if this is really necessary.

**Comment by proninyaroslav** [comment]
Well, yes, it's quite an old fb2, but it can be opened by any well-known reader, for example Caliber or Librera Reader. I think there are quite a lot of non-standard fb2 in the world and their support would be a big plus.

**Comment by proninyaroslav** [comment]
As a compromise, it might be possible to add an option, something like `fb2c convert --decode-html-entity book.fb2` , which would first passed the text through an HTML character decoder, and then convert it to EPUB/etc.

**Comment by rupor-github** [comment]
I wish it would be that simple. Here is a [full list of names](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references) to be added as an entity map to current XML parser. I'll think about how feasible this is and how to do it...

**Comment by proninyaroslav** [comment]
Not quite so, I suggest passing the file contents through a third-party decoder library (maybe it's even in the Go standard library) and then parse XML and so.

**Comment by proninyaroslav** [comment]
This will not be super efficient of course, but since it will not be used often, I think this is not a critical time, and it is much less than the time to independently decode these HTML entities through some tool or programming language.

**Comment by rupor-github** [comment]
Let's not design staff without looking at the code? Before answering I actually looked - everything is already passed through go standard XML parser with HTML decoder explicitly specified - this is what you have today. As I said - I will think about it.

**Comment by proninyaroslav** [comment]
I tried to decode via JS library and now the conversion was successful. It seems to contain all possible entities, maybe it will be useful to you https://github.com/mathiasbynens/he/tree/master/data

**Comment by rupor-github** [comment]
https://github.com/rupor-github/fb2converter/releases/tag/v1.75.4
