### ISSUE TITLE
Correct app name

### ISSUE THREAD

**Issue by Korb** [rupor-github/fb2converter#23]
What is the exact name of this application? **fb2converter**, **FB2 converter to EPUB2, KEPUB, MOBI 7/8, AZW3** or **fb2mobi**? Currently, all three options are found on the application page.

I suggest choosing and using only this one. This will make the application more recognizable and popular, which will also contribute to increasing the attention of programmers who can make it even better.

**Comment by rupor-github** [comment]
Could you please be a bit more specific? What application page?

**Comment by rupor-github** [comment]
I would happily look at the PR with better README suggestions.

**Comment by Korb** [comment]
> Could you please be a bit more specific?

@rupor-github, [fixed](https://github.com/rupor-github/fb2converter/issues/23#issue-2605099950)
