### ISSUE TITLE
Behavior of the `ignore_nonbreakable_space` setting

### ISSUE THREAD

**Issue by Korb** [rupor-github/fb2converter#24]
Currently in [configuration.toml](https://github.com/rupor-github/fb2converter/blob/master/static/configuration.toml) it says:

```
#---- When breaking sentences into words nbsp symbols are considered to be part of the word.
# This will replace all nbsp symbols with ordinary spaces,
# potentially breaking original formatting and changing hyphenation
# ignore_nonbreakable_space = false
```

This wording can be interpreted as either "ignore nbsp symbols, keeping them in the output file" or "ignore nbsp symbols, replacing them with a space character".

I suggest rephrasing the comment to make it unambiguous.

**Comment by rupor-github** [comment]
I will try again - are you referring to the name of the setting or the comment to the setting? Which part is "this" in your statement?

If I remember correctly name of the setting was kept from previous project - fb2mobi to simplify transition and comment was put to explain what exactly being done. I do not see how it can be improved without changing the name of the setting. Is that what you are suggesting?

**Comment by rupor-github** [comment]
Please, submit a PR or an example with "unambiguous" wording in the comment. I did my best and fail to see any ambiguity in existing sentences. ChatGPT for once tend to agree with me.

**Comment by Korb** [comment]
> rupor-github added the question label 3 hours ago
> rupor-github added the (wontfix label 18 minutes ago

@rupor-github, as I understand, you found the answers to the questions [asked](https://github.com/rupor-github/fb2converter/issues/24#issuecomment-2429149329) to me, and answered them? My congratulations to you and ChatGPT!
