### ISSUE TITLE
fb2mobi.exe only accept 1 directory deep output path

### ISSUE THREAD

**Issue by stasts** [rupor-github/fb2converter#7]
When using fb2mobi wrapper, then output directory cut. In my example, I'm passing "Z:\BookExport\_MOBI_EXPORT" as target directory, but fb2c receive only "Z:\\BookExport". See output below:

E:\Books\converters\fb2mobi>fb2mobi.exe "C:\Users\STSARE~1\AppData\Local\Temp\_myhomelib\01 - Agent na myagkih lapah.fb2" "Z:\BookExport\_MOBI_EXPORT"
Starting E:\Books\converters\fb2converter\fb2c.exe with ["-mhl" "2" "convert" "--ow" "C:\\Users\\STSARE~1\\AppData\\Loca
l\\Temp\\_myhomelib\\01 - Agent na myagkih lapah.fb2" "Z:\\BookExport"]
2020-12-30T10:31:54.023+0100    INFO    Using defaults (no configuration file)
2020-12-30T10:31:54.024+0100    INFO    Processing starting     {"source": "C:\\Users\\STSARE~1\\AppData\\Local\\Temp\\_
myhomelib\\01 - Agent na myagkih lapah.fb2", "destination": "Z:\\BookExport", "format": "mobi"}
2020-12-30T10:31:54.024+0100    INFO    Conversion starting     {"from": "01 - Agent na myagkih lapah.fb2"}
2020-12-30T10:31:54.306+0100    WARN    Removing cover image duplicates, leaving only the first one
2020-12-30T10:31:57.325+0100    WARN    Overwriting existing file       {"file": "Z:\\BookExport\\01 - Agent na myagkih
lapah.mobi"}
2020-12-30T10:31:57.459+0100    INFO    Conversion completed    {"elapsed": "3.4352107s", "to": "Z:\\BookExport\\01 - Ag
ent na myagkih lapah.mobi"}
2020-12-30T10:31:57.459+0100    INFO    Processing completed    {"elapsed": "3.4352107s"}

**Comment by rupor-github** [comment]
When using fb2mobi wrapper you cannot specify output directory - only a full path to the resulting file. So in your case it should be  `fb2mobi.exe "C:\Users\STSARE1\AppData\Local\Temp_myhomelib\01 - Agent na myagkih lapah.fb2" "Z:\BookExport_MOBI_EXPORT\01 - Agent na myagkih lapah.fb2". This is by design and done for compatibility with original converters (python's fb2mobi). Program interprets second parameter as a full path to file and in order to calculate the directory cuts the last part.

**Comment by stasts** [comment]
Thank you for feedback. But I think it's still a bug. Original fb2mobi accept either path to resulting file or directory. In 2nd case it use original file name of the fb2 file (optional parameters -us ). Your wrapper actually do the same, but cutting directory for last part. 
For example I'm running following:
_c:\Books\convertes\fb2mobi>fb2mobi.exe "C:\temp\something.fb2" "D:\BookExport\MOBI"_

With your logic, when 2nd parameter is full path to resulting file, then result should be file "**MOBI**" in directory **D:\BookExport**. But in reality, it create file "**something.mobi**" (use filename of the original fb2 file) and put it to **D:\BookExport**. 

It's not really important issue, because I can pass extra fake directory level that would be cut (as example "**D:\BookExport\MOBI\NOT_EXISTED_DIR**") and it would be behavior I need: same file name as original file in directory  **D:\BookExport\MOBI**.

Anyway, thank you again for great converted that work with modern fb2 files :+1:

**Comment by rupor-github** [comment]
😀

Original `fb2mobi` indeed accepts path and/or dir, but not when called form `myhomelib` - it is special case as far as I could remember (different command line processing to support this). `fb2mobi` and `fb2epub` wrappers are only intended to be called by `myhomelib`, not directly, so full support was never planned.  As the result we have a combination of factors:

1. `fb2c` itself does not allow specifying output file, only directory for it
2.  wrappers are only intended to be called from `myhomelib` and have no way of knowing what is being requested - directory or file
3. Historically `myhomelib` provides file name at the end of second parameter, at list this how it was when I wrote wrappers code.

So code does following: takes second parameter, expands path to be absolute and cuts last path without even looking at it. 

```
	to, err := filepath.Abs(os.Args[2])
	if err != nil {
		log.Fatal(err)
	}
	to = filepath.Dir(to)
	if _, err := os.Stat(to); err != nil {
		log.Fatal("Destination directory does not exist", to, err)
	}
```

It was never intended to be more complex than that. If you want proper checking and directory support - call `fb2c` directly or write your own script, it should be simple...
