### ISSUE TITLE
multiseries support

### ISSUE THREAD

**Issue by CkNoSFeRaTU** [rupor-github/fb2converter#9]
I'm often stumble upon books which have multiple series sequence tags like in this example:
```
<?xml version="1.0" encoding="UTF-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
<description>
  <title-info>
    [...]
    <sequence name="Main Series Name"/>
    <sequence name="Sub Series Name" number="1"/>
  </title-info>
</description>
```
Currently fb2converter only looks for the first one and ignores all subsequent sequences. So it losing not only more relevant subseries name but more importantly book number in the series. Are there any plans to support that?

I'm hacked around the problem like this:
```
--- a/processor/process.go
+++ b/processor/process.go
@@ -672,9 +672,14 @@ func (p *Processor) processDescription() error {
                                        p.Book.Authors = append(p.Book.Authors, an)
                                }
                        }
-                       if e := info.SelectElement("sequence"); e != nil {
+                       for _, e := range info.SelectElements("sequence") {
                                var err error
-                               p.Book.SeqName = getAttrValue(e, "name")
+                               name := getAttrValue(e, "name")
+                               if name == "" {
+                                       p.env.Log.Warn("Sequence name is not defined", zap.String("xml", getXMLFragmentFromElement(e)))
+                                       continue
+                               }
+                               p.Book.SeqName = filepath.Join(p.Book.SeqName, name)
                                num := getAttrValue(e, "number")
                                if len(num) > 0 {
                                        if !govalidator.IsNumeric(num) {

```
But that's obviously a dirty hack and Book.SeqName/Book.SeqNum needs to be replaced with array like Book.Authors to cleanly support that. Maybe with some additional configuration parameters determining how to deal with them.

**Comment by rupor-github** [comment]
To get all the series info into Book structure as an array/slice is not difficult, what I do not know is how they should be used later?

**Comment by rupor-github** [comment]
This subject was brought up multiple times before, however suitable solution has not yet been found. See for example: https://www.mobileread.com/forums/showthread.php?t=267382. I do not see a way to handle this properly, open for any suggestion (except concatenation - due to multiple obvious problems like size of the resulting string or absence of clear way of handling multiple series indices).
